# Generated by Django 5.2 on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("title", models.CharField(max_length=120, verbose_name="Title")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="Slug")),
                ("image_url", models.URLField(max_length=500, verbose_name="Image URL")),
                (
                    "size",
                    models.CharField(
                        choices=[("large", "Large"), ("small", "Small"), ("wide", "Wide")],
                        default="small",
                        max_length=10,
                        verbose_name="Size",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Expedition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("slug", models.SlugField(max_length=170, unique=True, verbose_name="Slug")),
                ("date_label", models.CharField(max_length=80, verbose_name="Date label")),
                ("description", models.TextField(verbose_name="Description")),
                ("image_url", models.URLField(max_length=500, verbose_name="Image URL")),
            ],
            options={
                "verbose_name": "Expedition",
                "verbose_name_plural": "Expeditions",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                (
                    "section",
                    models.CharField(
                        choices=[("header", "Header"), ("footer", "Footer")],
                        max_length=20,
                        verbose_name="Section",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Title")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                ("href", models.CharField(max_length=200, verbose_name="Href")),
            ],
            options={
                "verbose_name": "Navigation item",
                "verbose_name_plural": "Navigation items",
                "ordering": ("section", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                (
                    "brand_name",
                    models.CharField(default="Romanweiss", max_length=120, verbose_name="Brand name"),
                ),
                (
                    "hero_kicker",
                    models.CharField(
                        default="Travel & Expedition Photography",
                        max_length=200,
                        verbose_name="Hero kicker",
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(default="Romanweiss", max_length=120, verbose_name="Hero title"),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        default="Exploring landscapes, architecture, and the distance between moments.",
                        verbose_name="Hero subtitle",
                    ),
                ),
                (
                    "hero_background_image",
                    models.URLField(
                        default="https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=2000&q=80",
                        max_length=500,
                        verbose_name="Hero background image",
                    ),
                ),
                (
                    "journal_intro",
                    models.TextField(
                        default="We travel not to escape life, but for life not to escape us. This journal is a collection of moments from the road - a visual diary of silence, texture, and light.",
                        verbose_name="Journal intro",
                    ),
                ),
                (
                    "expeditions_eyebrow",
                    models.CharField(default="The Journal", max_length=80, verbose_name="Expeditions eyebrow"),
                ),
                (
                    "expeditions_title",
                    models.CharField(
                        default="Recent Expeditions", max_length=120, verbose_name="Expeditions title"
                    ),
                ),
                (
                    "expeditions_subtitle",
                    models.CharField(
                        default="Journeys into the remote.",
                        max_length=220,
                        verbose_name="Expeditions subtitle",
                    ),
                ),
                (
                    "expeditions_action_label",
                    models.CharField(
                        default="View all ->",
                        max_length=80,
                        verbose_name="Expeditions action label",
                    ),
                ),
                (
                    "categories_eyebrow",
                    models.CharField(default="Portfolio", max_length=80, verbose_name="Categories eyebrow"),
                ),
                (
                    "categories_title",
                    models.CharField(default="Fields of Focus", max_length=120, verbose_name="Categories title"),
                ),
                (
                    "categories_subtitle",
                    models.CharField(
                        default="Visual separation through imagery, not boxes.",
                        max_length=220,
                        verbose_name="Categories subtitle",
                    ),
                ),
                (
                    "stories_eyebrow",
                    models.CharField(default="Visual Stories", max_length=80, verbose_name="Stories eyebrow"),
                ),
                (
                    "stories_title",
                    models.CharField(default="Selected Stories", max_length=120, verbose_name="Stories title"),
                ),
                (
                    "story_action_label",
                    models.CharField(
                        default="Read full story",
                        max_length=80,
                        verbose_name="Story action label",
                    ),
                ),
                (
                    "contact_title",
                    models.CharField(default="Get in touch", max_length=120, verbose_name="Contact title"),
                ),
                (
                    "contact_description",
                    models.TextField(
                        default="Interested in a collaboration, a print, or just want to say hello? I am always open to discussing new projects and creative opportunities.",
                        verbose_name="Contact description",
                    ),
                ),
                (
                    "contact_location",
                    models.CharField(
                        default="Berlin, Germany",
                        max_length=200,
                        verbose_name="Contact location",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="hello@romanweiss.com", max_length=254, verbose_name="Contact email"
                    ),
                ),
                (
                    "footer_title",
                    models.CharField(default="Romanweiss", max_length=120, verbose_name="Footer title"),
                ),
                (
                    "footer_description",
                    models.TextField(
                        default="Capturing the silence of remote places, the texture of the wind, and the stories found in distance.",
                        verbose_name="Footer description",
                    ),
                ),
                (
                    "footer_explore_title",
                    models.CharField(default="Explore", max_length=80, verbose_name="Footer explore title"),
                ),
                (
                    "footer_social_title",
                    models.CharField(default="Social", max_length=80, verbose_name="Footer social title"),
                ),
                (
                    "footer_newsletter_title",
                    models.CharField(default="Newsletter", max_length=80, verbose_name="Footer newsletter title"),
                ),
                (
                    "newsletter_note",
                    models.CharField(
                        default="Updates from the road, once a month.",
                        max_length=200,
                        verbose_name="Newsletter note",
                    ),
                ),
            ],
            options={"verbose_name": "Site settings", "verbose_name_plural": "Site settings"},
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("title", models.CharField(max_length=80, verbose_name="Title")),
                ("slug", models.SlugField(max_length=100, unique=True, verbose_name="Slug")),
                ("short_label", models.CharField(max_length=12, verbose_name="Short label")),
                ("url", models.CharField(blank=True, max_length=300, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Social link",
                "verbose_name_plural": "Social links",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                ("slug", models.SlugField(max_length=170, unique=True, verbose_name="Slug")),
                ("date_label", models.CharField(max_length=80, verbose_name="Date label")),
                ("description", models.TextField(verbose_name="Description")),
                ("image_url", models.URLField(max_length=500, verbose_name="Image URL")),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
                "ordering": ("order", "id"),
            },
        ),
    ]
