# Generated by Django 5.2 on 2026-02-08

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_seed_initial_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="seo_description",
            field=models.CharField(blank=True, max_length=320, verbose_name="SEO description"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="seo_image",
            field=models.URLField(blank=True, max_length=500, verbose_name="SEO image URL"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="seo_title",
            field=models.CharField(blank=True, max_length=255, verbose_name="SEO title"),
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="categories_eyebrow",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="categories_subtitle",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="categories_title",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contact_description",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contact_location",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="contact_title",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="expeditions_action_label",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="expeditions_eyebrow",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="expeditions_subtitle",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="expeditions_title",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_background_image",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_kicker",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_subtitle",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="hero_title",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="journal_intro",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="stories_eyebrow",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="stories_title",
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="story_action_label",
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("code", models.SlugField(max_length=50, unique=True, verbose_name="Code")),
                ("title", models.CharField(max_length=120, verbose_name="Title")),
                (
                    "location",
                    models.CharField(
                        choices=[("main", "Main"), ("footer", "Footer"), ("social", "Social")],
                        default="main",
                        max_length=20,
                        verbose_name="Location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("seo_title", models.CharField(blank=True, max_length=255, verbose_name="SEO title")),
                (
                    "seo_description",
                    models.CharField(blank=True, max_length=320, verbose_name="SEO description"),
                ),
                ("seo_image", models.URLField(blank=True, max_length=500, verbose_name="SEO image URL")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(max_length=160, unique=True, verbose_name="Slug")),
                ("is_home", models.BooleanField(default=False, verbose_name="Home page")),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("key", models.SlugField(max_length=80, verbose_name="Key")),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("rich_text", "Rich text"),
                            ("cards", "Cards"),
                            ("gallery", "Gallery"),
                            ("stories", "Stories"),
                            ("contact", "Contact"),
                        ],
                        max_length=32,
                        verbose_name="Section type",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, verbose_name="Title")),
                ("subtitle", models.CharField(blank=True, max_length=320, verbose_name="Subtitle")),
                ("body", models.TextField(blank=True, verbose_name="Body")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="Payload")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="content.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page section",
                "verbose_name_plural": "Page sections",
                "ordering": ("page_id", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="SectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("image_url", models.URLField(max_length=500, verbose_name="Image URL")),
                ("alt_text", models.CharField(blank=True, max_length=255, verbose_name="Alt text")),
                ("caption", models.CharField(blank=True, max_length=255, verbose_name="Caption")),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="content.pagesection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section image",
                "verbose_name_plural": "Section images",
                "ordering": ("section_id", "order", "id"),
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("label", models.CharField(max_length=120, verbose_name="Label")),
                ("href", models.CharField(blank=True, max_length=255, verbose_name="Href")),
                ("open_in_new_tab", models.BooleanField(default=False, verbose_name="Open in new tab")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.menu",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="menu_items",
                        to="content.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu item",
                "verbose_name_plural": "Menu items",
                "ordering": ("menu_id", "order", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                condition=Q(is_home=True),
                fields=("is_home",),
                name="content_single_home_page",
            ),
        ),
        migrations.AddConstraint(
            model_name="pagesection",
            constraint=models.UniqueConstraint(
                fields=("page", "key"), name="content_unique_page_section_key"
            ),
        ),
    ]
