# Generated by Django 5.2 on 2026-02-09

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_full_ru_zh_localization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="brand_name",
            field=models.CharField(
                default="Romanweiẞ", max_length=120, verbose_name="Brand name"
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="footer_title",
            field=models.CharField(
                default="Romanweiẞ", max_length=120, verbose_name="Footer title"
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("code", models.CharField(max_length=12, unique=True, verbose_name="Code")),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("is_default", models.BooleanField(default=False, verbose_name="Default")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TranslationKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("key", models.CharField(max_length=220, unique=True, verbose_name="Key")),
                ("namespace", models.CharField(blank=True, max_length=80, verbose_name="Namespace")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="Description")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Translation key",
                "verbose_name_plural": "Translation keys",
                "ordering": ("namespace", "key"),
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="content.translationkey",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="content.language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translation",
                "verbose_name_plural": "Translations",
                "ordering": ("language__order", "key__key"),
            },
        ),
        migrations.AddConstraint(
            model_name="language",
            constraint=models.UniqueConstraint(
                condition=Q(is_default=True),
                fields=("is_default",),
                name="content_single_default_language",
            ),
        ),
        migrations.AddConstraint(
            model_name="translation",
            constraint=models.UniqueConstraint(
                fields=("language", "key"),
                name="content_unique_language_translation_key",
            ),
        ),
    ]
