# Generated by Django 5.2 on 2026-02-09

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


DEFAULT_SITE_TEXTS = {
    "status.loading": {
        "en": "Loading content...",
        "ru": "Загрузка контента...",
        "zh": "正在加载内容...",
    },
    "status.unavailable": {
        "en": "Content is unavailable.",
        "ru": "Контент недоступен.",
        "zh": "内容不可用。",
    },
    "lang.en": {"en": "EN", "ru": "EN", "zh": "EN"},
    "lang.ru": {"en": "RU", "ru": "RU", "zh": "RU"},
    "lang.zh": {"en": "中文", "ru": "中文", "zh": "中文"},
    "lang.switcher": {"en": "Language", "ru": "Язык", "zh": "语言"},
    "theme.light": {"en": "Light", "ru": "Светлая", "zh": "浅色"},
    "theme.dark": {"en": "Dark", "ru": "Тёмная", "zh": "深色"},
    "detail.location": {"en": "Location", "ru": "Локация", "zh": "地点"},
    "detail.email": {"en": "Email", "ru": "Почта", "zh": "邮箱"},
    "detail.socials": {"en": "Socials", "ru": "Соцсети", "zh": "社交"},
    "form.name.label": {"en": "Name", "ru": "Имя", "zh": "姓名"},
    "form.name.placeholder": {"en": "Your name", "ru": "Ваше имя", "zh": "你的姓名"},
    "form.email.label": {"en": "Email", "ru": "Почта", "zh": "邮箱"},
    "form.email.placeholder": {"en": "your@email.com", "ru": "your@email.com", "zh": "your@email.com"},
    "form.message.label": {"en": "Message", "ru": "Сообщение", "zh": "留言"},
    "form.message.placeholder": {
        "en": "Tell me about your project...",
        "ru": "Расскажите о вашем проекте...",
        "zh": "请介绍一下你的项目...",
    },
    "form.submit": {"en": "Send message", "ru": "Отправить сообщение", "zh": "发送消息"},
    "form.sending": {"en": "Sending...", "ru": "Отправка...", "zh": "发送中..."},
    "form.success": {
        "en": "Message sent. Thank you.",
        "ru": "Сообщение отправлено. Спасибо.",
        "zh": "消息已发送。谢谢。",
    },
    "form.error": {"en": "Could not send message.", "ru": "Не удалось отправить сообщение.", "zh": "发送失败。"},
    "newsletter.placeholder": {"en": "Email address", "ru": "Email адрес", "zh": "邮箱地址"},
    "newsletter.button": {"en": "Join", "ru": "Подписаться", "zh": "订阅"},
}


STORY_I18N_MAP = {
    "echoes-of-the-mountain": {
        "title": {"ru": "Эхо гор", "zh": "山之回响"},
        "description": {
            "ru": "Почему мы идём вверх, когда мир предлагает остаться внизу.",
            "zh": "当世界劝我们低头时，我们为何仍选择攀登。",
        },
    },
    "lost-in-the-fog": {
        "title": {"ru": "Потерянные в тумане", "zh": "雾中迷途"},
        "description": {
            "ru": "Утренняя прогулка, которая превратилась в путешествие внутрь себя.",
            "zh": "一次清晨散步，最终成了向内的旅程。",
        },
    },
}


def _is_external_url(value: str) -> bool:
    lowered = value.lower()
    return lowered.startswith("http://") or lowered.startswith("https://") or lowered.startswith("mailto:")


def seed_source_of_truth(apps, schema_editor):
    SiteText = apps.get_model("content", "SiteText")
    TranslationKey = apps.get_model("content", "TranslationKey")
    Translation = apps.get_model("content", "Translation")
    NavigationItem = apps.get_model("content", "NavigationItem")
    Page = apps.get_model("content", "Page")
    Story = apps.get_model("content", "Story")
    SocialLink = apps.get_model("content", "SocialLink")

    translation_map: dict[int, dict[str, str]] = {}
    for key_id, lang_code, text in Translation.objects.values_list("key_id", "language__code", "text"):
        if not lang_code or not text:
            continue
        bucket = translation_map.setdefault(key_id, {})
        bucket[str(lang_code).lower()] = text

    for key_row in TranslationKey.objects.all():
        values = translation_map.get(key_row.id, {})
        en_text = values.get("en") or key_row.key
        i18n = {code: text for code, text in values.items() if code != "en" and text}
        SiteText.objects.update_or_create(
            key=key_row.key,
            defaults={
                "group": key_row.namespace,
                "description": key_row.description,
                "text": en_text,
                "text_i18n": i18n,
                "is_published": key_row.is_active,
            },
        )

    for key, values in DEFAULT_SITE_TEXTS.items():
        namespace = key.split(".", 1)[0] if "." in key else "core"
        row, _ = SiteText.objects.get_or_create(
            key=key,
            defaults={
                "group": namespace,
                "description": "",
                "text": values["en"],
                "text_i18n": {
                    code: text for code, text in values.items() if code != "en" and text
                },
                "is_published": True,
            },
        )

        updated_fields = []
        if not row.text:
            row.text = values["en"]
            updated_fields.append("text")
        current_i18n = dict(row.text_i18n or {})
        for code, text in values.items():
            if code == "en" or not text:
                continue
            if not current_i18n.get(code):
                current_i18n[code] = text
        if current_i18n != (row.text_i18n or {}):
            row.text_i18n = current_i18n
            updated_fields.append("text_i18n")
        if updated_fields:
            row.save(update_fields=updated_fields)

    pages_by_slug = {
        page.slug: page.id for page in Page.objects.all()
    }
    home_page_id = next((page_id for slug, page_id in pages_by_slug.items() if slug == "home"), None)

    site_text_by_key = {
        row.key: row for row in SiteText.objects.filter(is_published=True)
    }

    for item in NavigationItem.objects.all():
        href = str(item.href or "").strip()
        menu = "main" if item.section == "header" else "footer"
        url_key = ""
        page_id = None
        external_url = ""
        open_in_new_tab = bool(item.open_in_new_tab)

        if href.startswith("#"):
            url_key = slugify(href[1:]) or href[1:]
        elif href.startswith("/"):
            stripped = href.strip("/")
            if not stripped and home_page_id:
                page_id = home_page_id
            elif stripped:
                page_slug = stripped.split("/", 1)[0]
                page_id = pages_by_slug.get(page_slug)
                if not page_id:
                    url_key = slugify(page_slug) or page_slug
        elif href:
            if _is_external_url(href):
                external_url = href
                open_in_new_tab = open_in_new_tab or href.lower().startswith(("http://", "https://"))
            else:
                url_key = slugify(href) or href

        if not url_key and not page_id and not external_url:
            url_key = slugify(item.slug) or slugify(item.title) or "item"

        token = url_key or slugify(item.slug) or slugify(item.title) or "item"
        key_candidates = (
            [f"social.{token}"]
            if menu == "social"
            else [f"footer.nav.{token}", f"nav.{token}"] if menu == "footer" else [f"nav.{token}", f"footer.nav.{token}"]
        )

        title_i18n = dict(item.title_i18n or {})
        for candidate in key_candidates:
            site_text = site_text_by_key.get(candidate)
            if site_text is None:
                continue
            text_i18n = dict(site_text.text_i18n or {})
            for code, translated in text_i18n.items():
                if translated and not title_i18n.get(code):
                    title_i18n[code] = translated
            break

        update_fields = []
        if item.menu != menu:
            item.menu = menu
            update_fields.append("menu")
        if item.url_key != url_key:
            item.url_key = url_key
            update_fields.append("url_key")
        if item.page_id != page_id:
            item.page_id = page_id
            update_fields.append("page")
        if item.external_url != external_url:
            item.external_url = external_url
            update_fields.append("external_url")
        if item.open_in_new_tab != open_in_new_tab:
            item.open_in_new_tab = open_in_new_tab
            update_fields.append("open_in_new_tab")
        if title_i18n != (item.title_i18n or {}):
            item.title_i18n = title_i18n
            update_fields.append("title_i18n")
        if update_fields:
            item.save(update_fields=update_fields)

    if not NavigationItem.objects.filter(menu="social").exists():
        max_order = (
            NavigationItem.objects.filter(menu="social")
            .order_by("-order")
            .values_list("order", flat=True)
            .first()
            or 0
        )
        for index, social in enumerate(SocialLink.objects.filter(is_published=True).order_by("order", "id"), start=1):
            title = social.short_label or social.title
            token = slugify(social.slug) or slugify(title) or f"social-{index}"
            href = social.url or "#"
            NavigationItem.objects.create(
                section="footer",
                menu="social",
                title=title,
                slug=f"social-{token}",
                url_key=token,
                external_url=href if _is_external_url(href) else "",
                href=href,
                open_in_new_tab=href.lower().startswith(("http://", "https://")),
                order=max_order + index,
                is_published=True,
            )

    for story in Story.objects.all():
        mapped = STORY_I18N_MAP.get(story.slug)
        if not mapped:
            continue
        title_i18n = dict(story.title_i18n or {})
        description_i18n = dict(story.description_i18n or {})

        changed = False
        for code, value in mapped.get("title", {}).items():
            if value and not title_i18n.get(code):
                title_i18n[code] = value
                changed = True
        for code, value in mapped.get("description", {}).items():
            if value and not description_i18n.get(code):
                description_i18n[code] = value
                changed = True

        if changed:
            story.title_i18n = title_i18n
            story.description_i18n = description_i18n
            story.save(update_fields=["title_i18n", "description_i18n"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_seed_i18n_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("key", models.CharField(max_length=220, unique=True, verbose_name="Key")),
                ("group", models.CharField(blank=True, max_length=80, verbose_name="Group")),
                ("description", models.CharField(blank=True, max_length=255, verbose_name="Description")),
                ("text", models.TextField(verbose_name="Text (EN)")),
                (
                    "text_i18n",
                    models.JSONField(blank=True, default=dict, verbose_name="Text translations"),
                ),
            ],
            options={
                "verbose_name": "Site text",
                "verbose_name_plural": "Site texts",
                "ordering": ("group", "order", "key"),
            },
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="external_url",
            field=models.CharField(blank=True, max_length=300, verbose_name="External URL"),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="menu",
            field=models.CharField(
                choices=[("main", "Main"), ("footer", "Footer"), ("social", "Social")],
                default="main",
                max_length=20,
                verbose_name="Menu",
            ),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="open_in_new_tab",
            field=models.BooleanField(default=False, verbose_name="Open in new tab"),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="navigation_items",
                to="content.page",
            ),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="Title translations"),
        ),
        migrations.AddField(
            model_name="navigationitem",
            name="url_key",
            field=models.SlugField(blank=True, max_length=120, verbose_name="URL key"),
        ),
        migrations.AddField(
            model_name="story",
            name="date_label_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="Date label translations"),
        ),
        migrations.AddField(
            model_name="story",
            name="description_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="Description translations"),
        ),
        migrations.AddField(
            model_name="story",
            name="title_i18n",
            field=models.JSONField(blank=True, default=dict, verbose_name="Title translations"),
        ),
        migrations.AlterModelOptions(
            name="navigationitem",
            options={
                "verbose_name": "Navigation item",
                "verbose_name_plural": "Navigation items",
                "ordering": ("menu", "order", "id"),
            },
        ),
        migrations.RunPython(seed_source_of_truth, noop_reverse),
    ]
