# Generated by Codex on 2026-02-09

from django.db import migrations, models
import django.db.models.deletion


MEDIA_DEFAULTS = {
    "hero": {
        "title": "Hero default",
        "static_path": "content/images/hero-default.svg",
        "alt_text": "Hero image",
    },
    "expedition": {
        "title": "Expedition default",
        "static_path": "content/images/expedition-default.svg",
        "alt_text": "Expedition image",
    },
    "category": {
        "title": "Category default",
        "static_path": "content/images/category-default.svg",
        "alt_text": "Category image",
    },
    "story": {
        "title": "Story default",
        "static_path": "content/images/story-default.svg",
        "alt_text": "Story image",
    },
}


def _upsert_site_text(SiteText, key: str, text: str, group: str, text_i18n: dict | None = None):
    SiteText.objects.update_or_create(
        key=key,
        defaults={
            "group": group,
            "description": "",
            "text": text,
            "text_i18n": text_i18n or {},
            "is_published": True,
        },
    )


def seed_django_first_content(apps, schema_editor):
    MediaAsset = apps.get_model("content", "MediaAsset")
    SiteText = apps.get_model("content", "SiteText")
    Page = apps.get_model("content", "Page")
    PageSection = apps.get_model("content", "PageSection")
    HeroSection = apps.get_model("content", "HeroSection")
    Expedition = apps.get_model("content", "Expedition")
    Category = apps.get_model("content", "Category")
    Story = apps.get_model("content", "Story")

    media_by_key = {}
    for key, payload in MEDIA_DEFAULTS.items():
        asset, _ = MediaAsset.objects.get_or_create(
            title=payload["title"],
            defaults={
                "static_path": payload["static_path"],
                "alt_text": payload["alt_text"],
                "order": 1,
                "is_published": True,
            },
        )
        update_fields = []
        if not asset.static_path:
            asset.static_path = payload["static_path"]
            update_fields.append("static_path")
        if not asset.alt_text:
            asset.alt_text = payload["alt_text"]
            update_fields.append("alt_text")
        if update_fields:
            asset.save(update_fields=update_fields)
        media_by_key[key] = asset

    _upsert_site_text(
        SiteText,
        "section.hero.cta_label",
        "View journeys",
        "section",
        {"ru": "Смотреть путь", "zh": "查看旅程"},
    )

    home_page = (
        Page.objects.filter(is_home=True, is_active=True, is_published=True).order_by("order", "id").first()
        or Page.objects.filter(is_active=True, is_published=True).order_by("order", "id").first()
    )

    if home_page:
        hero_source = (
            PageSection.objects.filter(page=home_page, key="hero", is_published=True)
            .order_by("order", "id")
            .first()
        )
        payload = hero_source.payload if hero_source and isinstance(hero_source.payload, dict) else {}

        hero, _ = HeroSection.objects.get_or_create(
            page=home_page,
            defaults={
                "key": payload.get("anchor") or "journey",
                "kicker": str(payload.get("kicker", "")).strip(),
                "title": hero_source.title if hero_source and hero_source.title else "Romanweiẞ",
                "subtitle": hero_source.subtitle if hero_source else "",
                "cta_label": str(payload.get("cta_label", "")).strip(),
                "cta_url": str(payload.get("cta_url", "#expeditions")).strip() or "#expeditions",
                "scroll_label": str(payload.get("scroll_label", "")).strip(),
                "media_id": media_by_key["hero"].id,
                "order": 1,
                "is_published": True,
            },
        )
        changed = False
        if not hero.media_id:
            hero.media_id = media_by_key["hero"].id
            changed = True
        if not hero.cta_url:
            hero.cta_url = "#expeditions"
            changed = True
        if changed:
            hero.save(update_fields=["media", "cta_url", "updated_at"])

    for expedition in Expedition.objects.all():
        changed = False
        if not expedition.subtitle:
            expedition.subtitle = expedition.description
            changed = True
        if not expedition.cover_id:
            expedition.cover_id = media_by_key["expedition"].id
            changed = True
        if expedition.image_url and expedition.image_url.startswith(("http://", "https://")):
            expedition.image_url = ""
            changed = True
        if changed:
            expedition.save(update_fields=["subtitle", "cover", "image_url", "updated_at"])

        _upsert_site_text(
            SiteText,
            f"expedition.{expedition.slug}.title",
            expedition.title,
            "expedition",
            {"ru": expedition.title, "zh": expedition.title},
        )
        _upsert_site_text(
            SiteText,
            f"expedition.{expedition.slug}.subtitle",
            expedition.subtitle or expedition.description,
            "expedition",
            {"ru": expedition.subtitle or expedition.description, "zh": expedition.subtitle or expedition.description},
        )
        _upsert_site_text(
            SiteText,
            f"expedition.{expedition.slug}.date_label",
            expedition.date_label,
            "expedition",
            {"ru": expedition.date_label, "zh": expedition.date_label},
        )

    for category in Category.objects.all():
        changed = False
        if not category.cover_id:
            category.cover_id = media_by_key["category"].id
            changed = True
        if category.image_url and category.image_url.startswith(("http://", "https://")):
            category.image_url = ""
            changed = True
        if changed:
            category.save(update_fields=["cover", "image_url", "updated_at"])

        _upsert_site_text(
            SiteText,
            f"category.{category.slug}.title",
            category.title,
            "category",
            {"ru": category.title, "zh": category.title},
        )

    for story in Story.objects.all():
        changed = False
        if not story.cover_id:
            story.cover_id = media_by_key["story"].id
            changed = True
        if story.image_url and story.image_url.startswith(("http://", "https://")):
            story.image_url = ""
            changed = True
        if changed:
            story.save(update_fields=["cover", "image_url", "updated_at"])

        title_i18n = dict(story.title_i18n or {})
        date_i18n = dict(story.date_label_i18n or {})
        description_i18n = dict(story.description_i18n or {})

        _upsert_site_text(
            SiteText,
            f"story.{story.slug}.title",
            story.title,
            "story",
            {"ru": title_i18n.get("ru") or story.title, "zh": title_i18n.get("zh") or story.title},
        )
        _upsert_site_text(
            SiteText,
            f"story.{story.slug}.date_label",
            story.date_label,
            "story",
            {"ru": date_i18n.get("ru") or story.date_label, "zh": date_i18n.get("zh") or story.date_label},
        )
        _upsert_site_text(
            SiteText,
            f"story.{story.slug}.description",
            story.description,
            "story",
            {
                "ru": description_i18n.get("ru") or story.description,
                "zh": description_i18n.get("zh") or story.description,
            },
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_content_source_of_truth"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("title", models.CharField(max_length=120, verbose_name="Title")),
                ("file", models.FileField(blank=True, upload_to="content/media/", verbose_name="File")),
                ("static_path", models.CharField(blank=True, max_length=255, verbose_name="Static path")),
                ("alt_text", models.CharField(blank=True, max_length=255, verbose_name="Alt text")),
            ],
            options={
                "verbose_name": "Media asset",
                "verbose_name_plural": "Media assets",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("key", models.SlugField(default="hero", max_length=80, verbose_name="Key")),
                ("kicker", models.CharField(blank=True, max_length=220, verbose_name="Kicker")),
                ("title", models.CharField(max_length=220, verbose_name="Title")),
                ("subtitle", models.CharField(blank=True, max_length=320, verbose_name="Subtitle")),
                ("cta_label", models.CharField(blank=True, max_length=120, verbose_name="CTA label")),
                ("cta_url", models.CharField(blank=True, max_length=255, verbose_name="CTA URL")),
                ("scroll_label", models.CharField(blank=True, max_length=120, verbose_name="Scroll label")),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hero_sections",
                        to="content.mediaasset",
                    ),
                ),
                (
                    "page",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero",
                        to="content.page",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero section",
                "verbose_name_plural": "Hero sections",
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="category",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="categories",
                to="content.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="expedition",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expeditions",
                to="content.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="expedition",
            name="subtitle",
            field=models.CharField(blank=True, max_length=220, verbose_name="Subtitle"),
        ),
        migrations.AddField(
            model_name="story",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stories",
                to="content.mediaasset",
            ),
        ),
        migrations.RunPython(seed_django_first_content, noop_reverse),
    ]
