# Generated by Codex on 2026-02-09

from django.db import migrations, models
import django.db.models.deletion


UI_TEXTS = {
    "expeditions.index.title": {
        "en": "Recent expeditions",
        "ru": "Последние экспедиции",
        "zh": "最新探险",
    },
    "expeditions.index.subtitle": {
        "en": "Routes through remote locations.",
        "ru": "Маршруты по удалённым локациям.",
        "zh": "通往偏远地点的路线。",
    },
    "expeditions.index.card_cta": {
        "en": "Open expedition",
        "ru": "Открыть экспедицию",
        "zh": "打开探险",
    },
    "expedition.detail.back": {
        "en": "Back to expeditions",
        "ru": "Назад к экспедициям",
        "zh": "返回探险列表",
    },
    "expedition.detail.media_title": {
        "en": "Media gallery",
        "ru": "Медиа-галерея",
        "zh": "媒体画廊",
    },
    "expedition.detail.story_title": {
        "en": "Field notes",
        "ru": "Полевые заметки",
        "zh": "现场笔记",
    },
    "expedition.detail.video_title": {
        "en": "Video diary",
        "ru": "Видео дневник",
        "zh": "影像记录",
    },
    "expedition.detail.video_placeholder": {
        "en": "Video placeholder",
        "ru": "Плейсхолдер видео",
        "zh": "视频占位",
    },
    "lightbox.open_image": {
        "en": "Open image",
        "ru": "Открыть изображение",
        "zh": "打开图片",
    },
    "lightbox.close": {"en": "Close", "ru": "Закрыть", "zh": "关闭"},
    "lightbox.prev": {"en": "Previous", "ru": "Назад", "zh": "上一张"},
    "lightbox.next": {"en": "Next", "ru": "Вперёд", "zh": "下一张"},
}


def _upsert_site_text(SiteText, key: str, group: str, values: dict[str, str]):
    SiteText.objects.update_or_create(
        key=key,
        defaults={
            "group": group,
            "description": "",
            "text": values["en"],
            "text_i18n": {
                "ru": values.get("ru", values["en"]),
                "zh": values.get("zh", values["en"]),
            },
            "is_published": True,
        },
    )


def seed_expedition_media(apps, schema_editor):
    Expedition = apps.get_model("content", "Expedition")
    ExpeditionMedia = apps.get_model("content", "ExpeditionMedia")
    SiteText = apps.get_model("content", "SiteText")

    for key, values in UI_TEXTS.items():
        _upsert_site_text(SiteText, key, "ui", values)

    for expedition in Expedition.objects.all():
        _upsert_site_text(
            SiteText,
            f"expedition.{expedition.slug}.description",
            "expedition",
            {
                "en": expedition.description,
                "ru": expedition.description,
                "zh": expedition.description,
            },
        )

        if ExpeditionMedia.objects.filter(expedition=expedition).exists():
            continue

        ExpeditionMedia.objects.create(
            expedition=expedition,
            kind="image",
            title="Cover frame",
            title_i18n={"ru": "Кадр обложки", "zh": "封面画面"},
            media=expedition.cover,
            image_url=expedition.image_url,
            alt_text=expedition.title,
            order=1,
            is_published=True,
        )
        ExpeditionMedia.objects.create(
            expedition=expedition,
            kind="story",
            title="Field notes",
            title_i18n={"ru": "Полевые заметки", "zh": "现场笔记"},
            body=expedition.description,
            body_i18n={
                "ru": expedition.description,
                "zh": expedition.description,
            },
            order=2,
            is_published=True,
        )
        ExpeditionMedia.objects.create(
            expedition=expedition,
            kind="video",
            title="Video diary",
            title_i18n={"ru": "Видео дневник", "zh": "影像记录"},
            video_url="",
            order=3,
            is_published=True,
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_django_first_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpeditionMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video"), ("story", "Story")],
                        default="image",
                        max_length=20,
                        verbose_name="Kind",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=180, verbose_name="Title")),
                (
                    "title_i18n",
                    models.JSONField(blank=True, default=dict, verbose_name="Title translations"),
                ),
                ("body", models.TextField(blank=True, verbose_name="Body")),
                (
                    "body_i18n",
                    models.JSONField(blank=True, default=dict, verbose_name="Body translations"),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, verbose_name="Image URL")),
                ("video_url", models.URLField(blank=True, max_length=500, verbose_name="Video URL")),
                ("alt_text", models.CharField(blank=True, max_length=255, verbose_name="Alt text")),
                (
                    "expedition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_items",
                        to="content.expedition",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expedition_media_items",
                        to="content.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expedition media",
                "verbose_name_plural": "Expedition media",
                "ordering": ("expedition_id", "order", "id"),
            },
        ),
        migrations.RunPython(seed_expedition_media, noop_reverse),
    ]
