# Generated by Codex on 2026-02-09

from django.db import migrations


EXPEDITION_IMAGE_URLS = {
    "glacial-highlands": "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=80",
    "desert-passage": "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80",
    "city-at-dawn": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1400&q=80",
}

CATEGORY_IMAGE_URLS = {
    "landscapes": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1400&q=80",
    "architecture": "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
    "nature": "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    "travel-series": "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1400&q=80",
}

STORY_IMAGE_URLS = {
    "echoes-of-the-mountain": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1400&q=80",
    "lost-in-the-fog": "https://images.unsplash.com/photo-1482192596544-9eb780fc7f66?auto=format&fit=crop&w=1400&q=80",
}


def restore_seed_photo_urls(apps, schema_editor):
    Expedition = apps.get_model("content", "Expedition")
    ExpeditionMedia = apps.get_model("content", "ExpeditionMedia")
    Category = apps.get_model("content", "Category")
    Story = apps.get_model("content", "Story")

    for slug, image_url in EXPEDITION_IMAGE_URLS.items():
        expedition = Expedition.objects.filter(slug=slug).first()
        if expedition is None:
            continue

        if not str(expedition.image_url or "").strip():
            expedition.image_url = image_url
            expedition.save(update_fields=["image_url", "updated_at"])

        ExpeditionMedia.objects.filter(
            expedition_id=expedition.id,
            kind="image",
            image_url="",
        ).update(image_url=image_url)

    for slug, image_url in CATEGORY_IMAGE_URLS.items():
        category = Category.objects.filter(slug=slug).first()
        if category is None:
            continue
        if not str(category.image_url or "").strip():
            category.image_url = image_url
            category.save(update_fields=["image_url", "updated_at"])

    for slug, image_url in STORY_IMAGE_URLS.items():
        story = Story.objects.filter(slug=slug).first()
        if story is None:
            continue
        if not str(story.image_url or "").strip():
            story.image_url = image_url
            story.save(update_fields=["image_url", "updated_at"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_expedition_media_and_ui_texts"),
    ]

    operations = [
        migrations.RunPython(restore_seed_photo_urls, noop_reverse),
    ]
