# Generated by Codex on 2026-02-12

from django.db import migrations, models
import django.db.models.deletion


UI_TEXTS = {
    "category.card.cta": {
        "en": "Open focus area",
        "ru": "Open focus area",
        "zh": "Open focus area",
    },
    "category.detail.back": {
        "en": "Back to focus areas",
        "ru": "Back to focus areas",
        "zh": "Back to focus areas",
    },
    "category.detail.gallery_title": {
        "en": "Gallery",
        "ru": "Gallery",
        "zh": "Gallery",
    },
}


CATEGORY_DESCRIPTIONS = {
    "landscapes": {
        "en": "Terrain studies, weather layers, and long-distance light.",
        "ru": "Terrain studies, weather layers, and long-distance light.",
        "zh": "Terrain studies, weather layers, and long-distance light.",
    },
    "architecture": {
        "en": "Geometry, material rhythm, and quiet urban frames.",
        "ru": "Geometry, material rhythm, and quiet urban frames.",
        "zh": "Geometry, material rhythm, and quiet urban frames.",
    },
    "nature": {
        "en": "Organic textures, motion in stillness, and natural patterns.",
        "ru": "Organic textures, motion in stillness, and natural patterns.",
        "zh": "Organic textures, motion in stillness, and natural patterns.",
    },
    "travel-series": {
        "en": "Connected visual diaries from routes and border zones.",
        "ru": "Connected visual diaries from routes and border zones.",
        "zh": "Connected visual diaries from routes and border zones.",
    },
}


def _upsert_site_text(SiteText, key: str, group: str, values: dict[str, str]):
    SiteText.objects.update_or_create(
        key=key,
        defaults={
            "group": group,
            "description": "",
            "text": values["en"],
            "text_i18n": {
                "ru": values.get("ru", values["en"]),
                "zh": values.get("zh", values["en"]),
            },
            "is_published": True,
        },
    )


def seed_category_gallery(apps, schema_editor):
    Category = apps.get_model("content", "Category")
    CategoryGalleryItem = apps.get_model("content", "CategoryGalleryItem")
    SiteText = apps.get_model("content", "SiteText")

    for key, values in UI_TEXTS.items():
        _upsert_site_text(SiteText, key, "ui", values)

    for slug, values in CATEGORY_DESCRIPTIONS.items():
        _upsert_site_text(SiteText, f"category.{slug}.description", "category", values)

    for category in Category.objects.all():
        if CategoryGalleryItem.objects.filter(category=category).exists():
            continue

        first_caption = f"{category.title} frame 1"
        second_caption = f"{category.title} frame 2"
        first_description = f"Primary visual note from {category.title}."
        second_description = f"Secondary visual note from {category.title}."

        CategoryGalleryItem.objects.create(
            category=category,
            title="Frame 1",
            title_i18n={"ru": "Frame 1", "zh": "Frame 1"},
            description=first_description,
            description_i18n={"ru": first_description, "zh": first_description},
            media=category.cover,
            image_url=category.image_url,
            alt_text=first_caption,
            order=1,
            is_published=True,
        )
        CategoryGalleryItem.objects.create(
            category=category,
            title="Frame 2",
            title_i18n={"ru": "Frame 2", "zh": "Frame 2"},
            description=second_description,
            description_i18n={"ru": second_description, "zh": second_description},
            media=category.cover,
            image_url=category.image_url,
            alt_text=second_caption,
            order=2,
            is_published=True,
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0012_restore_seed_photo_urls"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryGalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Order")),
                ("is_published", models.BooleanField(default=True, verbose_name="Published")),
                ("title", models.CharField(blank=True, max_length=180, verbose_name="Title")),
                (
                    "title_i18n",
                    models.JSONField(blank=True, default=dict, verbose_name="Title translations"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "description_i18n",
                    models.JSONField(blank=True, default=dict, verbose_name="Description translations"),
                ),
                ("image_url", models.URLField(blank=True, max_length=500, verbose_name="Image URL")),
                ("alt_text", models.CharField(blank=True, max_length=255, verbose_name="Alt text")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_items",
                        to="content.category",
                    ),
                ),
                (
                    "media",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category_gallery_items",
                        to="content.mediaasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category gallery item",
                "verbose_name_plural": "Category gallery items",
                "ordering": ("category_id", "order", "id"),
            },
        ),
        migrations.RunPython(seed_category_gallery, noop_reverse),
    ]
