# Generated by Codex on 2026-02-12

from django.db import migrations


UI_TEXTS = {
    "stories.index.card_cta": {
        "en": "Open story",
        "ru": "Open story",
        "zh": "Open story",
    },
    "story.detail.back": {
        "en": "Back to stories",
        "ru": "Back to stories",
        "zh": "Back to stories",
    },
}


def seed_story_ui_texts(apps, schema_editor):
    SiteText = apps.get_model("content", "SiteText")
    for key, values in UI_TEXTS.items():
        SiteText.objects.update_or_create(
            key=key,
            defaults={
                "group": "ui",
                "description": "",
                "text": values["en"],
                "text_i18n": {
                    "ru": values.get("ru", values["en"]),
                    "zh": values.get("zh", values["en"]),
                },
                "is_published": True,
            },
        )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0013_category_gallery_and_focus_pages"),
    ]

    operations = [
        migrations.RunPython(seed_story_ui_texts, noop_reverse),
    ]
